// This file was generated by Prisma
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "/Users/Aamer/Desktop/kurapath/prisma/schema.prisma",
  migrations: {
    path: "/Users/Aamer/Desktop/kurapath/prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});

console.log("Prisma Config: DATABASE_URL is " + (process.env["DATABASE_URL"] ? "defined" : "undefined"));
